#!/bin/bash
#
# Shorebird patch helper for Turbo Traffic Rush (turbo_traffic_rush).
#
# Ships Dart-only changes to an existing release without a store review. Native
# and asset changes cannot travel in a patch — those need a new release
# (./scripts/shorebird_release.sh). Because every WAV under assets/audio/ is
# generated by scripts/generate_audio.py, re-running that script is an asset
# change: it needs a release, not a patch.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/shorebird_common.sh
source "$SCRIPT_DIR/lib/shorebird_common.sh"

ENTRY_POINT="lib/main.dart"

print_header "Turbo Traffic Rush — Shorebird Patch"

require_shorebird
require_auth
cd "$PROJECT_ROOT"
require_shorebird_project

print_color "Version in pubspec.yaml: $(project_version)" "$GREEN"

print_header "Existing Releases"
shorebird releases list 2>&1 || print_color "⚠ Could not list releases; see https://console.shorebird.dev" "$YELLOW"

echo ""
echo "Select platform to patch:"
echo "1) Android"
echo "2) iOS"
echo "3) Both"
read -r -p "Enter choice (1-3): " PLATFORM_CHOICE
case $PLATFORM_CHOICE in
    1|2|3) ;;
    *)
        print_color "Invalid choice: $PLATFORM_CHOICE" "$RED"
        exit 1
        ;;
esac

# A patch is built against one release version. "latest" is what the CLI itself
# understands, so the two branches differ only in the value.
echo ""
echo "Target release version:"
echo "1) Latest release (default)"
echo "2) Specific version (e.g. $(project_version))"
read -r -p "Enter choice (1-2): " VERSION_CHOICE

TARGET_VERSION="latest"
if [ "$VERSION_CHOICE" = "2" ]; then
    read -r -p "Enter release version to patch (e.g. 2.0.2+11): " TARGET_VERSION
    if [ -z "$TARGET_VERSION" ]; then
        print_color "No version given." "$RED"
        exit 1
    fi
fi
print_color "Patching release: $TARGET_VERSION" "$CYAN"

# The patch runs against whatever is in the working tree — a stray debug tweak
# would go straight to every installed device.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    echo ""
    print_color "⚠ Uncommitted changes in the working tree go into this patch:" "$YELLOW"
    git status --short | head -20
    [ "$(git status --porcelain | wc -l)" -gt 20 ] && print_color "  ... (truncated)" "$YELLOW"
    echo ""
    if ! confirm "Continue anyway?"; then
        print_color "Patch cancelled." "$RED"
        exit 0
    fi
fi

print_header "Patch Configuration"
case $PLATFORM_CHOICE in
    1) print_color "Platform: Android" "$YELLOW" ;;
    2) print_color "Platform: iOS" "$YELLOW" ;;
    3) print_color "Platform: Android & iOS" "$YELLOW" ;;
esac
print_color "Release:  $TARGET_VERSION" "$YELLOW"
print_color "Entry:    $ENTRY_POINT" "$YELLOW"
echo ""
if ! confirm "Deploy this patch?"; then
    print_color "Patch cancelled." "$RED"
    exit 0
fi

run_patch() {
    local platform=$1
    print_header "Patching $platform"
    resolve_dart_defines "$platform"
    shorebird patch -p "$platform" --target "$ENTRY_POINT" \
        --release-version="$TARGET_VERSION" "${DART_DEFINE_ARGS[@]}"
}

case $PLATFORM_CHOICE in
    1) run_patch "android" ;;
    2) run_patch "ios" ;;
    3)
        run_patch "android"
        run_patch "ios"
        ;;
esac

print_header "Patch Deployment Complete!"
print_color "✅ Patch deployed to release $TARGET_VERSION" "$GREEN"
echo ""
print_color "Reminders:" "$YELLOW"
print_color "• Devices pick the patch up on the next launch, online" "$NC"
print_color "• Dart-only: changes under android/, ios/ or assets/ need a new release" "$NC"
print_color "• A patch cannot change the pubspec version users see" "$NC"
echo ""
print_color "Next steps:" "$BLUE"
print_color "• Track adoption: shorebird patches list --release-version $TARGET_VERSION" "$CYAN"
print_color "• Console: https://console.shorebird.dev" "$CYAN"
print_color "• Smoke-test a patched device: run, crash, garage, paywall" "$CYAN"
